### ISSUE TITLE
Can't add a non-member account without publishing identity

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#106]
I wanted to add an account into Cutecoin for pure transactions purposes.

However, when adding the account and choosing a node, I am asked if I want to publish my identity on the server. If I say "No", I the window closes but I still have to select a node.

The only way to escape is to accept to publish the identity. Could we create the account withtout publishing identity?

**Comment by Insoleet** [comment]
Well that's because we want the uid of the account published on the network that we ask the user to publish its identity. 

Anonymous identities were supposed to be derived wallets in cutecoin. Well we still need to have a talk about what are wallets, what are account... Because everybody wants something different right now :D

**Comment by Insoleet** [comment]
AS the bug is currently a feature, we will talk about it for the 1.0.

**Comment by Insoleet** [comment]
In the meantime, I propose the following : 
- UID publishing should not be mandatory
- The tab "Wallets" would display a status about uid "published" in green, "not published" in red
- Just one question remains : should setting an uid to an account be mandatory ?

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/221ed42fb250dde334d99b119c90e9fba666dce4
