### ISSUE TITLE
Differences/Issues between 0.10.1 stable and dev branch

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#163]
* **Wallet tab** where you can see I don't have same quantity of money in UD (~10 <-> ~11 DU MB):
 * **stable**:
![wallet_tab_stable](https://cloud.githubusercontent.com/assets/4758871/8463156/b2ab78d0-2038-11e5-909c-a63a46cfd4bc.png)
 * **dev**:
![wallet_tab_dev](https://cloud.githubusercontent.com/assets/4758871/8463185/cdefac7e-2038-11e5-81af-ed7e4a40c37f.png)

* **Transaction tab** where you can see there is not all transactions, for instance 16 and 17 june are not here:
 * **stable**:
![tx_tab_stable](https://cloud.githubusercontent.com/assets/4758871/8463231/0d4941d2-2039-11e5-801b-ed07d676869d.png)
 * **dev**:
![tx_tab_dev](https://cloud.githubusercontent.com/assets/4758871/8463234/141e24f0-2039-11e5-901f-5be96bd9d011.png)

* **Network tab** on dev version where it is displayed two times same server:
![network_tab_dev](https://cloud.githubusercontent.com/assets/4758871/8463385/349ed98a-203a-11e5-8c8f-5899f2b2de8e.png)

**Comment by Insoleet** [comment]
Thanks a lot for the report.

Could you please check something on the dev version : 

 - Remove the files [pubkey]_wal in your __cache__ folder
 - Remove the file [currency]_bma in your cache folder
 - Restart cutecoin and check content of the transactions
 - Restart cutecoin a second time if display is incorrect
What happens when you are doing this ?

Thanks in advance !

**Comment by M5oul** [comment]
I am always removing `__cache__` repository before launching CuteCoin.

**Comment by Insoleet** [comment]
Analyzed tonight, it's a ucoin bug https://github.com/ucoin-io/ucoin/issues/143

**Comment by M5oul** [comment]
All those issues seems to be fixes excepted transaction tab.
