### ISSUE TITLE
Crash when sorting in network tab

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#238]
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/network.py", line 40, in lessThan
    return (left_data < right_data)
TypeError: unorderable types: str() < int()
```

I have try to solved that type error, but I don't understand the [code](https://github.com/ucoin-io/cutecoin/blob/dev/src/cutecoin/models/network.py#L34-L40).

**Comment by Insoleet** [comment]
Well you would need a python debugger to access the values of left_data and right_data when this crashes. You should definitely get Pycharm when you want to work on cutecoin.

The bug is actually simple, when the cell is empty, the data returned is "". So with columns containing a number and an empty cell, it tries to compare "" to the number... And it crashes because you cannot compare a string to an int. 
Since in Python, everything can be casted to a string, we just have to cast the data returned to a string and it works ! :+1:

**Comment by M5oul** [comment]
Great, thanks, I will try PyCharm :smile:
