### ISSUE TITLE
Crash with a debug function when canceling a transaction

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#247]
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 290, in cancel_transfer
    transfer.cancel()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/transfer.py", line 327, in cancel
    self.run_state_transitions(())
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/transfer.py", line 319, in run_state_transitions
    if self._try_transition(key, inputs):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/transfer.py", line 301, in _try_transition
    logging.debug("{0} : {1} --> {2}".format(self.sha_hash[:5], self.state.name,
TypeError: 'NoneType' object is not subscriptable
```
I have try to remove this tree variables, the bug is still present. I don't know where it come from.

**Comment by Insoleet** [comment]
Subscriptable error are raised by the operator []. Here it means that the sha_hash is None. It was probably not initialized... Have to find why.

**Comment by Insoleet** [comment]
I can't reproduce this bug. Can you describe how you did it, what did you send, how, when did you cancel ?

**Comment by M5oul** [comment]
I sent money to cchaudier the 6 november. The transction didn't succeed (it's blue highlighted). I have try to cancel the transaction, then it crash. I have try to cancel it today.

**Comment by M5oul** [comment]
This crash is still present. Why did you close the issue?

**Comment by Insoleet** [comment]
Because the bug is not the line with the crash, it's a combination of two problems : 
 - When you sent this transaction, the coroutine probably crashed during the broadcast
 - Thus, no sha_hash was defined, because at this time, when a coroutine crashed, it would get stuck but not crash the software.( https://github.com/ucoin-io/cutecoin/commit/2fe37e7c46671a2ba9039f20c63930de2aaa0576 )
 - The bug is still present for your old transaction since it was in error before the fix, but after the fix, no transaction could have a sha_hash with a None value. It does not happen anymore with the new transaction !

**Comment by M5oul** [comment]
Ok
