### ISSUE TITLE
Network: the actual list of nodes is not displayed

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#264]
I can see in uCoin that we have the following known peers:

```
Key                                          | Host           | Port  | State
------------------------------------------------------------------------
CnRzLoh8BgBvjDSUFmqNXtxtf2SBoNb6jkzw3dw2r4Sh | 88.174.120.187 | 45001 | 41912
EtReqMNL4Gz4MmHL131X1p2MyfhDTxx3YPqZNrkVbcf5 | moul.re        | 8999  | 41912
GRcnHumHmrFgs8i2iATfn7gqWk8tf4G52pKd9VA1bSoS | 178.62.51.52   | 64353 | 41912
HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk | metab.ucoin.io | 9201  | 41912
J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3 | moul.re        | 8999  | 41912
```

But CuteCoin shows me:

![image](https://cloud.githubusercontent.com/assets/969136/11341081/2b21804a-9201-11e5-9fd1-2a517a9d8180.png)

**Comment by c-geek** [comment]
Relaunching CuteCoin gives this:

![image](https://cloud.githubusercontent.com/assets/969136/11341868/827ef716-9204-11e5-9fcb-71191b92d8cc.png)

**Comment by Insoleet** [comment]
Two problems : 
 - I just realized I'm missing a call to `_check_nodes_unique` in `handle_identity_change` at https://github.com/ucoin-io/cutecoin/blob/dev/src/cutecoin/core/net/network.py#L333 but it's not linked to this bug
 
- Possible scenario of the impossibility to detect the node J78bP before reboot : 
  - Cutecoin does not detect the pubkey change of moul.re (from J78bP to EtReq)
  - Cutecoin detect the new nodes with pubkey J78bP
  - It ignores the node since it has the same pubkey as one node it already knows
  - The merkle tree of peers is cached
  - The merkle tree of peers does not change, so when EtReq changes its pubkey from J78bP to EtReq, it never detects the new node
   - Reboot clears the cached merkle tree so it is able to detect the new node

**Comment by Insoleet** [comment]
The race condition is not probable with a large network. Thus, it is not necessary to try to fix this.
