### ISSUE TITLE
GUI internationalized (french to start)

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#52]
GUI should handle many languages.

Language should be detected from the system or choose in a configuration panel of the application.

**Comment by Insoleet** [comment]
I initialized the work to be done there : https://github.com/ucoin-io/cutecoin/commit/ed099703267b9f9129f1f11a774c7efda1d01625

**Comment by yvgithub** [comment]
Maybe more than just in the GUI: internationalization support in the comment of transaction.

**Comment by Insoleet** [comment]
What do you mean ? :o

**Comment by yvgithub** [comment]
I would like to be able to write: facture de méditation instead of facture de meditation in the comment of a transaction.
meditation -> méditation 
electricite -> électricité
voila -> voilà
etc.
![internationalsupport](https://cloud.githubusercontent.com/assets/1395647/7417761/6a5c2530-ef36-11e4-8441-c02f5a59c111.png)

**Comment by Insoleet** [comment]
This is a ucoin limitation, not a cutecoin one. You should post about it in https://github.com/ucoin-io/ucoin

**Comment by yvgithub** [comment]
Ok sorry my bad, thanks

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/0f83e3041e7a00d5c09cd4c3269357969b65cdaa
