### ISSUE TITLE
UI enhancements proposal

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#63]
The Quantitative and Relative Zero seems wrong, transactions appear with "-". It is the wallet only that is impacted. Wallet account is : x mb - M/N, with maximum credit (negative) : - M/N that must appear. : 

Solde | limit
x mb - M/N | -M/N

But transactions don't move at all they are the same as in quantative refererencial !

Idem for Relative Zero : 

Solde | Limit
(x mb - M/N) / UD | -(M/N)/UD

And transactions are the same as in UD referencial.

I suggest in the transaction Tab : 

- to put the account at the beggining of the dates at the bottom (always visible), and the account at the end of the dates at the top (always visible too), since we should be able to check the account and operations from date to date in the same TAB.

- to show the UD transactions, they don't appear at the moment, but the UD is a transaction ! Isn't it !?

I suggest for the "Wallet TAB" those informations : 

- A boxline with all wallet general information : Name of the wallet, ID, pubkey, number of signs from, number of signs to, date of beggining, next end date of validation, with ability to click on each information to go to the corresponding TAB to have more details.

- A boxline with the referencial choosen : Q,R,QZ,RZ with full name and a link towards help to read information.

- A boxline with : 
Balance (Solde in french) | Limit ... examples (not calculated exactly just to show) : 
437 mb | 0 mb (quantitative)
4 UDmb | 0 UD mb (relative)
10 mb | - 427 mb (quantitative zero)
4 UDmb | - 9,5 UD mb (relative zero)

- At the bottom the two buttons "renew membership", "leaving demand"

**Comment by Insoleet** [comment]
A lot of things have been done.

What I hesitate at working on are the following points : 
 - to put the account at the beggining of the dates at the bottom (always visible), and the account at the end of the dates at the top (always visible too), since we should be able to check the account and operations from date to date in the same TAB.
  - Hard to do and I don't see the what would be the point of such a feature.

 - to show the UD transactions, they don't appear at the moment, but the UD is a transaction ! Isn't it !?
  - Impossible to do in the current API state, since we have no way to know if an individual was a member in a past block without doing huge calculations.

 - A boxline with the referencial choosen : Q,R,QZ,RZ with full name and a link towards help to read information.
  - I'm not a huge fan of helps withing softwares. A good software shouldn't need any help. Technical details and calculations should be available for the one interested on the internet !

 - At the bottom the two buttons "renew membership", "leaving demand"
  - Why in the wallets tab ?
